// React
import React from 'react';

// Next
import Head from 'next/head';

// Contentful
import client from '/contentful/contentful.data';

// Components
import HeroImage from '../../components/hero-image/hero-image.component';
import SeperationHeader from '../../components/seperation-header/seperation-header.component';
import DetailsSection from '../../components/details-section/details-section.component';
import CarouselSlider from '../../components/carousel/carousel.component';

// Images

// Data

// Styles
import styled from 'styled-components';

export async function getStaticProps() {

  const resHeaders = await client.getEntries({
    content_type: 'header'
  });
  const resultHeader = Array.from(resHeaders.items).filter(item => item.fields.route == '/sport');

  const resSportSections = await client.getEntries({
    content_type: 'sportSection'
  });
  const resultSportSections = Array.from(resSportSections.items).sort((a, b) => parseInt(a.fields.order) - parseInt(b.fields.order));

  const resBrands = await client.getEntries({
    content_type: 'sportBrands'
  });
  const resultBrands = Array.from(resBrands.items).sort((a, b) => parseInt(a.fields.order) - parseInt(b.fields.order));

  return {
    props: {
      header: resultHeader,
      sportSections: resultSportSections,
      brands: resultBrands
    },
    revalidate: 1
  };
};

const Sport = ({ header, sportSections, brands }) => {
  return (
    <>
      <Head>
        <title>PJC Sport & Cycles - Sport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <HeroImage content={header} />
        <SeperationHeader childrenLvl1='Sport Equipment' />
        <DetailsSection content={sportSections} />
        <CarouselSlider content={brands} />
      </main>
    </>
  );
};

export default Sport;
