// React
import React from 'react';

// Next
import Head from 'next/head';

// Contentful
import client from '/contentful/contentful.data';

// Components
import HeroImage from '../../components/hero-image/hero-image.component';
import SeperationHeader from '../../components/seperation-header/seperation-header.component';
import TradingHours from '../../components/components-contact/trading-hours/trading-hours.component';
import MapLocation from '../../components/components-contact/map/map.component';
import ContactForm from '../../components/components-contact/contact-form/contact-form.component';

// Images

// Data

// Styles
import styled from 'styled-components';

export async function getStaticProps() {

  const resHeaders = await client.getEntries({
    content_type: 'header'
  });

  const resultHeader = Array.from(resHeaders.items).filter(item => item.fields.route == '/contact');

  return {
    props: {
      header: resultHeader
    },
    revalidate: 1
  };
};

const MapContactContainer = styled.div`
  display: flex;
  width: 80%;
  justify-content: space-between;
  align-items: center;
  margin: 0 auto;
`;

const Contact = ({ header }) => {
  return (
    <div>
      <Head>
        <title>PJC Sport & Cycles - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroImage content={header} />
      <SeperationHeader childrenLvl1='Trading Hours' />
      <TradingHours />
      <MapContactContainer>
        <MapLocation />
        <ContactForm />
      </MapContactContainer>
    </div>
  );
};

export default Contact;
