// React
import React from 'react';

// Next
import Head from 'next/head';

// Contentful
import client from '/contentful/contentful.data';

// Components
import SeperationHeader from '/components/seperation-header/seperation-header.component';
import WhatWeOfferContainer from '/components/components-home/what-we-offer/what-we-offer-container.component';
import SpecialsContainer from '../components/components-home/specials-container/specials-container.component';
import WeekendRides from '../components/components-home/weekend-rides/weekend-rides.component';
import HeroImage from '../components/hero-image/hero-image.component';

// Images

// Data
import monthName from '../functions/home.functions';

// Styles

export async function getStaticProps() {

  const resWwo = await client.getEntries({
    content_type: 'whatWeOffer'
  });

  const resultWwo = Array.from(resWwo.items).sort((a, b) => parseInt(a.fields.order) - parseInt(b.fields.order));

  const resSpecials = await client.getEntries({
    content_type: 'special'
  });

  const resultSpecials = Array.from(resSpecials.items).sort((a, b) => parseInt(a.fields.order) - parseInt(b.fields.order));

  const resHeaders = await client.getEntries({
    content_type: 'header'
  });

  const resultHeader = Array.from(resHeaders.items).filter(item => item.fields.route == '/');

  return {
    props: {
      whatWeOfferCards: resultWwo,
      specials: resultSpecials,
      header: resultHeader
    },
    revalidate: 1
  };
};

const Home = ({ whatWeOfferCards, specials, header }) => {
  return (
    <div>
      <Head>
        <title>PJC Sport & Cycles - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroImage content={header} />
        <SeperationHeader
          childrenLvl1={'What We Offer'} />
        <WhatWeOfferContainer content={whatWeOfferCards} />
        <SeperationHeader
          childrenLvl1={monthName}
          childrenLvl2={'Specials'} />
        <SpecialsContainer content={specials} />
        <WeekendRides />
      </main>
    </div>
  );
};

export default Home;