// React
import React from 'react';

// Next
import Head from 'next/head';
import Image from 'next/image';

// Contentful
import client from '/contentful/contentful.data';

// Components
import BicycleSkeleton from '../../components/skeletons/bicycle-skeleton';

// Images

// Data

// Styles
import styled from 'styled-components';
import BicycleSpecifications from '../../components/components-bicycles/bicycle-details-specifications/bicycle-details-specifications.component';

export const getStaticPaths = async () => {
  const res = await client.getEntries({
    content_type: 'bicycle'
  });

  const paths = res.items.map(item => {
    return {
      params: {
        slug: item.fields.name
      }
    }
  });

  return {
    paths,
    fallback: true
  };
};

export const getStaticProps = async ({ params }) => {
  const { items } = await client.getEntries({
    content_type: 'bicycle',
    'fields.name': params.slug
  });

  if (!items.length) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props:
    {
      bicycle: items[0]
    },
    revalidate: 1
  };
};

const Main = styled.main`
  background: url(${props => props.backgroundImg}) top / 100% no-repeat;
`;

const Buffer = styled.div`
  height: 80px;
`;

const Details = styled.div`
  position: relative;
  /* top: -3rem; */
`;

const DetailsContainer = styled.div`
  width: 90%;
  margin: 0 auto;
`;

const DetailsHeading = styled.div`
  position: relative;
  text-align: center;
  border-radius: 0.5rem 0.5rem 0 0;
  bottom: -3.5rem;
  /* z-index: 1; */
  background: transparent;
  height: 100vh;

  h1 {
    font-size: 10rem;
    margin: 0;
    color: rgba(235, 235, 235, 0.7);
    text-shadow: 5px 5px 10px rgba(0, 0, 0, 0.2);
    text-transform: uppercase;
  }
`;

const DetailsSection = styled.div`
  display: flex;
  flex-direction: column;
  border-radius: 0 0 0.5rem 0.5rem;
  background: #ffffff70;
`;

const DetailsTopSection = styled.div`

  .image-container {
    position: relative;
    display: flex;
    flex-direction: row;
    justify-content: center;
    margin: 0 auto;
    /* padding: 3rem; */
    /* background: #313131; */

    .image {
      height: fit-content;
    }
  }

  .description-container {
    /* padding: 0 0 1rem; */
    
    .description-text {
      width: 90%;
      margin: 0 auto;
    }
  }
`;

const DetailsBottomSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1rem;

  .top {
    padding-top: 2rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;

    .available-sizes {
      display: flex;
      flex-direction: row;
      
      .sizes {
        display: flex;
        flex-direction: row;
        justify-content: flex-start;
        text-decoration: none;
        list-style: none;
        margin: 0;
        
        li {
          padding: 0 5px;
          margin: 0;
        }
      }
    }

    .price {
      font-weight: 600;

      .price-was {
        font-weight: 400;
        text-decoration: line-through;
        color: #808080;
      }
    }
  }
`;

const Price = styled.div`
  display: flex;
  flex-direction: row;
  gap: 1rem;
  justify-content: space-between;
`;

const BicycleDetails = ({ bicycle }) => {
  if (!bicycle) {
    return (
      <BicycleSkeleton />
    )
  };

  const {
    name,
    brand,
    model,
    description,
    frameMaterial,
    availableSizes,
    fork,
    rearShock,
    chainwheel,
    frontDerailleur,
    rearDerailleur,
    shifters,
    chain,
    cassette,
    bottomBracket,
    speed,
    brakes,
    wheels,
    frontHub,
    rearHub,
    tyres,
    stem,
    seatPost,
    extras,
    priceNow,
    priceWas,
    detailsImage,
    detailsImageWidth,
    detailsImageHeight,
    altText,
    onSpecial } = bicycle.fields;

  var specs = {
    frameMaterial,
    fork,
    rearShock,
    chainwheel,
    frontDerailleur,
    rearDerailleur,
    shifters,
    chain,
    cassette,
    bottomBracket,
    speed,
    brakes,
    wheels,
    frontHub,
    rearHub,
    tyres,
    stem,
    seatPost,
    extras
  };

  var sizes = '';

  availableSizes.map(size => {
    sizes += size;
  });

  return (
    <div>
      <Head>
        <title>PJC Sport & Cycles - {brand} {model}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main
        backgroundImg={'https:' + detailsImage.fields.file.url}>
        <Buffer />
        <Details>
          <DetailsContainer>
            <DetailsHeading>
              <h1>{brand} {model}</h1>
            </DetailsHeading>
            <DetailsSection>
              <DetailsTopSection>
                {/* <div className='image-container'>
                  <Image className='rounded-corners' src={'https:' + detailsImage.fields.file.url} width={detailsImageWidth} height={detailsImageHeight} alt={altText} />
                </div> */}
                <div className='description-container'>
                  <div className='description-text'>
                    <h3>Description</h3>
                    <p>{description}</p>
                  </div>
                </div>
              </DetailsTopSection>
              <DetailsBottomSection>
                <div className='top'>
                  <h3>Details</h3>
                  <div className='available-sizes'>
                    <div>
                      <span className='bold'>Avaialable sizes: {sizes}</span>
                    </div>
                  </div>
                  <span className='bold'>Price:
                    {onSpecial ?
                      <Price>
                        <div className='price-now'> R{priceNow}.00</div>
                        <div className='price-was'> R{priceWas}.00</div>
                      </Price>
                      :
                      <span className='price-now'> R{priceNow}.00</span>
                    }
                  </span>
                </div>
                <div className='bottom'>
                  <h3>Specifications</h3>
                  <BicycleSpecifications content={specs} />
                </div>
              </DetailsBottomSection>
            </DetailsSection>
          </DetailsContainer>
        </Details>
      </Main>
    </div>
  );
};

export default BicycleDetails;