// React
import React from 'react';

// Next
import Head from 'next/head';
import Image from 'next/image';

// Contentful
import client from '/contentful/contentful.data';

// Components
import BicycleSkeleton from '../../components/skeletons/bicycle-skeleton';

// Images

// Data

// Styles
import styled from 'styled-components';
import BicycleSpecifications from '../../components/components-bicycles/bicycle-details-specifications/bicycle-details-specifications.component';

export const getStaticPaths = async () => {
  const res = await client.getEntries({
    content_type: 'bicycle'
  });

  const paths = res.items.map(item => {
    return {
      params: {
        slug: item.fields.name
      }
    }
  });

  return {
    paths,
    fallback: true
  };
};

export const getStaticProps = async ({ params }) => {
  const { items } = await client.getEntries({
    content_type: 'bicycle',
    'fields.name': params.slug
  });

  if (!items.length) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props:
    {
      bicycle: items[0]
    },
    revalidate: 1
  };
};

const Main = styled.main`
  background: url(${props => props.backgroundImg}) top / 100% no-repeat;
`;

const Details = styled.div`
  position: relative;
`;

const DetailsContainer = styled.div`
  width: 80%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
`;

const DetailsHeading = styled.div`
  position: relative;
  padding-top: 5rem;
  text-align: center;
  border-radius: 0.5rem 0.5rem 0 0;
  height: 100vh;

  h1 {
    font-size: 6rem;
    margin: 0;
    color: rgba(235, 235, 235, 0.7);
    text-shadow: 5px 5px 10px rgba(0, 0, 0, 0.2);
    text-transform: uppercase;
  }
`;

const DetailsSection = styled.div`
  display: flex;
  flex-direction: column;
  background: rgba(var(--grey-background), 0.05);
  padding: 2rem;
  margin-bottom: 2rem;
`;

const DetailsTopSection = styled.div`

`;

const DescriptionText = styled.div`
  margin: 0 auto;
`;

const DetailsBottomSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

const Top = styled.div`
  padding-top: 2rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
`;

const TopContent = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
`;

const AvailableSizes = styled.div`
  display: flex;
  flex-direction: row;
`;

const Sizes = styled.ul`
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  text-decoration: none;
  list-style: none;
  margin: 0;
  padding-left: 0;
  
  li {
    padding: 0 5px;
    margin: 0;
  }
`;

const PriceContainer = styled.div`
  
`;

const Price = styled.div`
  display: flex;
  flex-direction: row;
  gap: 1rem;
  justify-content: end;
`;

const PriceWas = styled.div`
  font-weight: 400;
  text-decoration: line-through;
  color: #808080;
`;

const PriceNow = styled.div`
  
`;

const BicycleDetails = ({ bicycle }) => {
  if (!bicycle) {
    return (
      <BicycleSkeleton />
    )
  };

  const {
    name,
    brand,
    model,
    description,
    frameMaterial,
    availableSizes,
    fork,
    rearShock,
    chainwheel,
    frontDerailleur,
    rearDerailleur,
    shifters,
    chain,
    cassette,
    bottomBracket,
    speed,
    brakes,
    wheels,
    frontHub,
    rearHub,
    tyres,
    stem,
    seatPost,
    extras,
    priceNow,
    priceWas,
    detailsImage,
    detailsImageWidth,
    detailsImageHeight,
    altText,
    onSpecial } = bicycle.fields;

  var specs = {
    frameMaterial,
    fork,
    rearShock,
    chainwheel,
    frontDerailleur,
    rearDerailleur,
    shifters,
    chain,
    cassette,
    bottomBracket,
    speed,
    brakes,
    wheels,
    frontHub,
    rearHub,
    tyres,
    stem,
    seatPost,
    extras
  };

  var sizes = '';

  availableSizes.map(size => {
    sizes += ' ' + size;
  });

  return (
    <div>
      <Head>
        <title>PJC Sport & Cycles - {brand} {model}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main
        backgroundImg={'https:' + detailsImage.fields.file.url}>
        <Details>
          <DetailsContainer>
            <DetailsHeading>
              <h1>{brand} {model}</h1>
            </DetailsHeading>
            <DetailsSection className='rounded-corners'>
              <DetailsTopSection>
                <DescriptionText>
                  <h2>Description</h2>
                  <p>{description}</p>
                </DescriptionText>
              </DetailsTopSection>
              <DetailsBottomSection>
                <Top>
                  <h2>Details</h2>
                  <TopContent>
                    <AvailableSizes>
                      <div>
                        <span className='bold'>Avaialable sizes: </span>
                      </div>
                      <Sizes>
                        {availableSizes.map(size => {
                          return (
                            <li key={size}>{size}</li>
                          )
                        })}
                      </Sizes>
                    </AvailableSizes>
                    <PriceContainer>
                      {onSpecial ?
                        <Price>
                          <span className='bold'>Price: </span>
                          <PriceWas>Was - R{priceWas}.00</PriceWas>
                          <PriceNow className='bold'>Now - R{priceNow}.00</PriceNow>
                        </Price>
                        :
                        <Price>
                          <span className='bold'>Price: </span>
                          <PriceNow className='bold'>R{priceNow}.00</PriceNow>
                        </Price>
                      }
                    </PriceContainer>
                  </TopContent>
                </Top>
                <div className='bottom'>
                  <h2>Specifications</h2>
                  <BicycleSpecifications content={specs} />
                </div>
              </DetailsBottomSection>
            </DetailsSection>
          </DetailsContainer>
        </Details>
      </Main>
    </div>
  );
};

export default BicycleDetails;