// React
import React from 'react';

// Next
import Head from 'next/head';

// Contentful
import client from '/contentful/contentful.data';

// Components
import HeroImage from '../../components/hero-image/hero-image.component';
import SeperationHeader from '../../components/seperation-header/seperation-header.component';
import BalletItemsContainer from '../../components/components-ballet/ballet-items-container/ballet-items-container.component';

// Images

// Data

// Styles
import styled from 'styled-components';

export async function getStaticProps() {

  const resHeaders = await client.getEntries({
    content_type: 'header'
  });
  const resultHeader = Array.from(resHeaders.items).filter(item => item.fields.route == '/ballet');

  const resBalletItems = await client.getEntries({
    content_type: 'ballet'
  });
  const resultBalletItems = Array.from(resBalletItems.items).sort((a, b) => parseInt(a.fields.order) - parseInt(b.fields.order));

  return {
    props: {
      header: resultHeader,
      ballet: resultBalletItems
    },
    revalidate: 1
  };
};

const Ballet = ({ header, ballet }) => {
  return (
    <>
      <Head>
        <title>PJC Sport & Cycles - Ballet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <HeroImage content={header} />
        <SeperationHeader childrenLvl1='Outfits & Accessories' />
        <BalletItemsContainer content={ballet} />
      </main>
    </>
  );
};

export default Ballet;
